travis:
  secure:
    BINSTAR_TOKEN: lMHrULwRBjPmsqTWIm1zH3uzih7+8Duq3QTBh3hGS8erv3fjzngXfGbJg307uahIqdwV54QPNKtWC9pwahWvvJ5qyB2c3/4VpivMHNWgo9WHjeeGhn+QhYgoOo+01u4kOge1DOhjC7ZAVlOi2UNKpb5hjjh3GvMPNk7OvS7gkscFufDt0YYEsKvBg3+tOFbq6DA6SBt+bAJOoPYCcJUTrGTJVEqV0uE2DgwtYRvAUmPLabYnbHx/4jocPcZ5/dy2LzNMB6bttnTGqBJ9oK1qHgPwRXUbg51/sWoPwFPsMMeEnC4EacxggB7Elg+CIfWqz8vBJBIw5JrwPyFso9aseIu0oYM/jeHl02z0V5qAiFMNNMw7mkDdtBGiPJtZRSvDF83mwBxC/DjO1Sewez2NeYp2zh/OeWFYqARF3FCGb6YNo3vhNmRaZNqZST5c6a8GduMOB47UY/s5VlsKHv82HiEW9isMtWyCHTsVv3yEvSZ6Y/o2Yo6JJvWyHmVvnRXObxLWVpIhmMtB8llqBVFKK4876Kl29ffGF1etIhyzRzyL9GiewjN5HaHsfsn/30WARQ1eOkUxOQAzb0WLn32HEygpBkn6/SAq1SuqhWbQBdUF3xQuus0lZILUFnhLX/APSr7CqYNzJE59koVJovF5GYXOCp/GPXM5Oc/zQC6FIrc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
