appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EmDM+kNIIYzXh0zEUMxcXTQ0jnQKK9aDMoUdY7lJCxwI4kAJRUA/KxvIJRz50L8q5nFs+hPxFHHIh9YF5QUpMlF5OWZ69YlaHDp+Cgevpdy180qIL4ABXeOUKny77tvF8WNf4uJhC6XDO2TzYelFuCPLz4cYTT5ibDQSYuX3cSoapuQAGsObt1ghJwGODiAluNZu2ksvNSHSVKfkjtTAvCbPEKk4Wkd3LrrhbY/lER4ROTqEJ7xMFzM/4NGzmir3nKxD95TBe8Kh6fu896ZnaJPFImT0M5O53yS+X6FzKshQBpFozk97bHZ8nw50EAmaZnGbrB7tMgN1/V0liI4gTHkWpWEM4t9q0ZR7wzPXQOCnKXw4qrrgsgKbqc3mljraDfimW2fGh9Rv/49L2WLh7cfhsyirAA8SvHCpSQI48DTMTrcNjIqjQzx3n2ejtuQkLNGOnjvmFx/hQJHGWWiJhqgPCsRxdRh4sVDTzEnQWvmYEn3YlQC9DuVvjFRK91Alqt+WEmOtW/TKAI0eUTstcmNsIEXDwIv+WQ63om7dBKi39lq6UlEZQYwgFJQbBrrI2Hyj6m8MB6YnQ0gvtVuVyxNfrTetIIC0tf2zZZDXMIFkNyrA11KFuzLzA6hLhmgjw5u0BcAX3r15TF4hDCbu4TMgu5vRDqezLVBdZR+Dsmo=}
provider:
  win: azure
