travis:
  secure:
    BINSTAR_TOKEN: FgUhR77rGMyNLfjdaDGVc1CatdSqOxdrh0lROSBV06eqNH/1o3KEbYIhah8U5ZkOPbTghPU+mhMer0p0SZkaO37qk+UHVeJ6og0Eysb+Mku+7YJqsR8KY9ExXlJsvcfJXWxRFC90H11/gxGRwoh4GqvLCc9nAQPmWBMiF0+dtLTyecYDB9oHczO6SZsVJ26KQbbV7Ax+n6zBdU16GrpXLeur1YKvAQ9OV3OJ9qKGg1v7NKRQIOf4c2RNcPYuF3b5j2J2lFTNe1bWKXfJ7CmupwjtgK8u9iM9tekHPhqRrECOvTnNvRUC3BaoNcO+clYjc7HiygTcHbCIABYIm3D/fOO718Lo+YI60wH7oS3eadh0punehxcfE2c/cUA0btfupog+mJFNWaswvPK84poP2hBwdZyMTaWSiJP9SrK3WMCSVzEI2cvBj+C9KP9BQH0JqXUKHoZfDIQt6J7ZXgb7Udpswg922MAgNAswm0pxt5H2NAtzmndgtjtuBi9qRTGNIdMMKgc4R0hagdWnDWuimsPKN0bACqjb2cqX8jvjc/r94hW7vWL/8C/VWKStaD5dNNzKpnHkbOUWlddUOwEOasUEMvlyTD3pJPhp4MIA7nof1KDytEqbW7QKQapcTVUgrNmONUXzjR7nQsvNvJtTA3cxO3BVIDTwy6bwUh1Gbc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
