appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VLiPW+QB1x4InZZLT1BNY5UwB85WCbRKPftNgxwALP4Xee4mWUnZRPjE7bOVJ3jhsN7rQ3BKVtSLxJBXMbURDY1foP2ERAMFpI/1qxUn8QWGkETDt7NGdSloIVPMoouEjN0VrnvNlFPbAloUwA0Z0d70fY6sNr5g4Z8eWQYB1jFyGKmF611SYwXwGct31q8rF2Lmbmn1YWO6GG7lsOWZfQ+I60B4jFDsGkPiXWps4PsqJT7ageB1klCagrmM0pPxNQ27HVmTHzzSnZnItM5CtPbLmFMhr+sClqQDQ1q6crJrc60ps2eM3Le0bFfmBv5+H2viUN8SRNMdBgWILXv2Z8qoOuE10xy4zc/vP7a6qrCA0azTwVOnSTl2tgrxl1ROs+z3Qy7hYzSr2X1sI2jOExUjEovcuBSKvVRl/nCuqHlrYNlqJ/mAbXWUe1dG+id51cKY7lAZn2VSI+4OqDVxf3A0la+MkCyDcjbn+Wu4lgo7MrAOubT3Lwt4Et4iMKeyRUHgD8nIQX5vpBNGoLU00jG2V2DeAMdVxeO1IWStRuu/SxwS4kTih8wBoYz1eTLvTc1OuALzoggHIlymqCBSgriuK0O/2FW5ZcEpznSBLYsp4jqnVIiuU/AFFKT9MnDAlPIqeNn47zzvbeBPx0BZBmVRX1mx8kEbhhZGUC9uSw4=}
