# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gHfNuxh8gJUbpKT6/ANtC1CyiF84exaWQL8oQ8zvIXLomq23NVJ00CE5w+hVQMJ2qc9Yz5QjSkgu97nPMtNyttzYA2wkEaHpPNX246hfXtbbX1ZYLkLqrVOCKO3c2qWA+R0wGha0L8G504pzn7vujV/ysVhiG9HwHJNSKJX+AfRg3IrjRY+jw0NEs5F47eXs9lFSYSLafsYxOsTMQLIWiXJKtiR1g9PGKnRyht7rRd7Zcbr4KryHnlXuBjXCQLXjMtGQiABTzXJDVoT3eWRf+rX8YhJ0dOJSZjkp15elbbU0w9O4gmKmYpZoPh3qKcuHze0/N1CARJPkii7sAtU7UL6i2i/yZsA/0pI/PlZ/lubfzL+7HBsOrQy39la1D+FSpi2loTGMQAP2q+kYTJUDPU+MH2Ab+Xvh0e/iEp0T7KHsLMeDx41QehhuLP+vz+0rMn9CXLrPcfsK9gUJqi+KjkxMbTJf+CbdNgOYWoe5nJknQwoK8uhVVWMpA8acl9p0w5/uYsu0AqdX4c5ucx67ZBufJJckyyp5hOz5Lxvsv697cMmcis+Ov6yanv2pKN7SxDqA4+tl3J2jaa165bOXcRfrxvELl/uDmBmNUFAHM3nChihLvWH8Q7hxrPFma3tZxiMgJ0KVvoYYW22+hrcQbbXZGthmhocQl/eIzNquz3I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
