travis:
  secure:
    BINSTAR_TOKEN: gHfNuxh8gJUbpKT6/ANtC1CyiF84exaWQL8oQ8zvIXLomq23NVJ00CE5w+hVQMJ2qc9Yz5QjSkgu97nPMtNyttzYA2wkEaHpPNX246hfXtbbX1ZYLkLqrVOCKO3c2qWA+R0wGha0L8G504pzn7vujV/ysVhiG9HwHJNSKJX+AfRg3IrjRY+jw0NEs5F47eXs9lFSYSLafsYxOsTMQLIWiXJKtiR1g9PGKnRyht7rRd7Zcbr4KryHnlXuBjXCQLXjMtGQiABTzXJDVoT3eWRf+rX8YhJ0dOJSZjkp15elbbU0w9O4gmKmYpZoPh3qKcuHze0/N1CARJPkii7sAtU7UL6i2i/yZsA/0pI/PlZ/lubfzL+7HBsOrQy39la1D+FSpi2loTGMQAP2q+kYTJUDPU+MH2Ab+Xvh0e/iEp0T7KHsLMeDx41QehhuLP+vz+0rMn9CXLrPcfsK9gUJqi+KjkxMbTJf+CbdNgOYWoe5nJknQwoK8uhVVWMpA8acl9p0w5/uYsu0AqdX4c5ucx67ZBufJJckyyp5hOz5Lxvsv697cMmcis+Ov6yanv2pKN7SxDqA4+tl3J2jaa165bOXcRfrxvELl/uDmBmNUFAHM3nChihLvWH8Q7hxrPFma3tZxiMgJ0KVvoYYW22+hrcQbbXZGthmhocQl/eIzNquz3I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
