appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider:
  linux: azure
  osx: azure
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
travis:
  secure: {BINSTAR_TOKEN: ZyWVzcPFxC4/9MRutvDCTM6h98KNyzH2iRiYkwfkA1w7mecW6T51Iao3xhxThgcV32j+bYGsH4t1yNZW9tFj6K67hIiXoFfFhFWReJyVHeKw9LkHMaPmT/ddZhh5dS8pevXywOgHBdMY05Wme7LvUkk5AjnrSKDQd2Z/czlXszI4cvWLV8M2F2wOlWXklljVq2KOtPxOfdCl+kntEVHRZdu0OVpImmbpyb7n3Ftd1DUSyzIMpGBDAutMX5ey43QKrKbh0hkqfsJDUaHIg9yfo22jdUftPPN0J/JRiaopGd9CieeioSy3YAtvMIPJzLhwadodbiYn2hIRXd90UAADr1heAVfRhjF7gfKJ4V9I6tcS0q5k3048xPFfqlDv+vkmTBOrnI1EPr3uoCuDiMR19wLdHUESWoT6bqkwdgLI8X9vbT/QXt8vsSV3D6p1olhEF1bmi/feAtav+q0B3rkG6adQ2BDF2xV8lebpxXkgsyjBD5s/DjglqGfZRiZKSGwvHGekF9hFJ2ioe3C1CcwKfACh0PnRGi6e6jI94N/D5cHf49vamGKqqL57xvR8ymVvUTrbU85jEe3y26uyJsrmkgBUmRNTmDE8WvmeN4yYRYOFCsP3QsUgSZWDLA1jbGCMkvLaP4pEvLBytKFedhRl5cULxLiZYi/QVMqDUU6CP88=}
conda_forge_output_validation: true
