{% set version = "7.1.2" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: a0b49960110bc6ff5fead46013bcb8825d101026d466f3a4de3476defe0fb0dd

build:
  number: 0
  skip: true  # [py==27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - zlib
    - libtiff
    - jpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL._imaging
    - PIL._imagingft
    - PIL._imagingmath
    - PIL._imagingmorph
    - PIL._imagingtk  # [linux and not (arm or ppc64le)]

about:
  home: https://pillow.readthedocs.io
  license: PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  description: |
    Pillow is the friendly PIL fork. PIL is the Python Imaging Library,
    adds image processing capabilities to your Python interpreter.
  doc_url: http://pillow.readthedocs.io/en/4.2.x/
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  dev_url: https://github.com/python-pillow/Pillow

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
