appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: HLCcFgA6TRVX8gvcyrDBJLCmBk2sFkX9H75joF9TTjRRdoMTH/Hm2XvTMio0Qa4z+j3rhGXwaw7o1F9mbXgNdO6y2YkEUbalofkZCVpKu8ybHwhgknPy03n2Pwc+5qVG1/nkWANCqF4rrx6pIM8T5NIH2abxBiozGgUShborLZezfWNYCPtmxRBSQb2K5me+gaVzTguVVp6Bi/n9zNiUuN7bG8KAH9aOV/nxmXquxhBA4di8UVbKg6ckBKMhPcbkGvmKos4Aubmm4dymPq8JF5yfmcrpXA3cGyA72FONRDS79JRt65MNlMc5lCph0UKtHa+UXCgDpZTlXx2F/mwXSF7VM2thX4GanYsLt098y7RC1I7qpvc2JLhQdr5ziyR2mvodae2Jm1odsqZe1bAg0K5sYZMkeyOWk0/XI2pw+NWCH2KGtJNxYXtEgaveBbAJAM7Dlx6qknFuAkNYhQVgEgFhhWkRWmg4eb0s4FJtNnSUAEHVE/tPp9C5pbn+Rdsxo5CHHr27rZpdbbuvZRcUzrH4+5cF+V0byzpDkaG6VMulqUyZlVL8DBfBgagsXnnkUA3bjGneQumKWwC5urnhNopkAF2ok0tRak1ug7400fyj0qBEUF9LLyhdGx5DmQl+y7VbX1lLpT1tNKaADSEhJMTqVoBa2de2ZndaUgLj9DA=}
