{% set version = "1.3.7" %}

package:
  name: nose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nose/nose-{{ version }}.tar.gz
  md5: 4d3ad0ff07b61373d2cefc89c5d0b20b
  patches:
    - win-rmentry.patch         # [win]

build:
  number: 1004
  entry_points:
    - nosetests = nose:run_exit

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  commands:
    - nosetests -h
  imports:
    - pkg_resources
    - nose

about:
  home: http://readthedocs.org/docs/nose/
  license: LGPL-2.1
  license_file: lgpl.txt
  summary: Nose extends unittest to make testing easier
  description: |
    NOTE: Nose has been in maintenance mode for the past several years and will
    likely cease without a new person/team to take over maintainership. New
    projects should consider using Nose2, py.test, or just plain
    unittest/unittest2.
  doc_url: https://nose.readthedocs.org
  dev_url: https://github.com/nose-devs/nose/

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - scopatz
    - ocefpaf
