{% set build_num = 1 %}
{% if python_impl_version is not defined %}
{% set python_impl_version = "3.9" %}
{% endif %}


package:
  name: python_abi
  version: {{ python_version }}

build:
  number: {{ build_num }}
  string: {{ build_num }}_{{ python_abi_tag }}


requirements:
  run:
    - {{ pin_compatible('python', exact=True) }}

test:
  commands:
    - python --version  # [python_impl == "cpython"]
    - pypy3 --version   # [python_impl == "pypy"]

about:
  home: https://github.com/conda-forge/python_abi-feedstock
  summary: Metapackage to select python implementation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
