{% set build_num = 1 %}
{% if python_impl_version is not defined %}
{% set python_impl_version = "3.6" %}
{% endif %}


package:
  name: python_abi
  version: {{ python_version }}

build:
  number: {{ build_num }}
  string: {{ build_num }}_{{ python_abi_tag }}


requirements:
  run:
    - python {{ python_impl_version }}.*                    # [python_impl == "cpython"]
    - pypy{{ python_version }} {{ python_impl_version }}.*  # [python_impl == "pypy"]
  run_constrained:
    - pypy <0a0                                                                         # [python_impl == "cpython"]
    - python {{ python_version }}.* *_{{ python_impl_version.replace('.', '') }}_pypy     # [python_impl == "pypy"]

test:
  commands:
    - python --version  # [python_impl == "cpython"]
    - pypy3 --version   # [python_impl == "pypy"]

about:
  home: https://github.com/conda-forge/python_abi-feedstock
  summary: Metapackage to select python implementation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
