travis:
  secure:
    BINSTAR_TOKEN: sQZytzgEjcJXDp0i7/lbzmAFwCKJwxspvrE3D9PquP0ye6LvbKfVKmolscaJoCQ1BH9kWE5Og2DAwiHE0wKjgySWiltJ5a0DjtvXjqLlV1rwXeTTDBSRsM1wjg1LCLn+FB8aoSvLEJLiek/+RfmmJQhy9mEkHF/yHhh6cACGQGXs9QVyYq1xCkocfXBfRgK7f63GtS6nQKL9Kt1sWk3IaUYcn039qUMuaFFIa/Vl6QKxQZHOpFoMx530Z6OXOFVeh46XZFzjBi98TBDAuf6ROW+gWyslW1EY1CeUyQlaBPIaur7eOpPV1hVqh0JE4qQJMJRczdJZy0Cfsl8JXzY9lUD7VODcCnilbDFR7C1KnYytaOCh9IFlhULejpYkOPPLcb+rY78C21qeaw4FjtQ/IPq56u0qFPscAKJe/UUgG5WaNghSTp7HedQ7jkZiCxNK21tL3T5u2hAigo5zy5Kb7UDZB1iqzvKR7s5dXARq8QzO1E9Y8Y5Mu5XOFRI6ditprlErZKQ+JHuh8hpSqzwf9X//WiZHLhD3dDc6dIhAL4xSA45k1Q+fWCIgqJ9/YKvYYuGvLrEdoUcpftWRFTgiVsjlXxP49bOaFaEiiyouDBxYk1xfQBj294TRY+AFgVgN3zlnDmClatevjkfZFsFhxOtGQz+RjSCrmqFanz+vhxI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
