appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider:
  linux: azure
  linux_aarch64: azure
  linux_ppc64le: azure
  osx: azure
  win: azure
travis:
  secure: {BINSTAR_TOKEN: mNvmmcna5PEorFrunEBQffYj44JctTq7VAVZLbJU2q+3pg0YfzhedVraNfC15ai1FMZ2q8KgovP9R8PZyZ/KUvuta6Ha6Uq9ols8fiI9jCb/BFpQ9pL/KQKnMQFSn4dH7eYKSBhgjhkIEUKykT523zaVxai0x41UPVe81ttkJVhO0mrVyW3UChK0V5FR4dfDU+r/1u5oG1Ak4V3JeYcffseD99DahG0LqPHzTiH/+XfM+qUmkzO781rvnkaJcFsaUvXFBXZi3CGnR5l8y7nlZyQoNFO2QSjcbeP0QvgnyQaPT9fMpGjTVsC7edeTdkioxIW/O8xlnfiFOQMtR7o8n6kVFOeS18Lq/vOKI6Po8vV0nE/DATm9GERHiqAw1Ps97vU/6uAGTaU6/7OFk9NhELdj9WpuhmrGIh2J6bxv4FNv0DUH4Grxt0/zsK1yz8cHU4zRrDdW7yHDdfZhhV4FTjTimkFWuHwjgfUqLeyhK2POn/4i3WPF/AM5vTgJ7pAZYnlWw7YLHaagXZRnYNB+gES6l6k2RzMFLKc9TNj3eHUHZr/w0SG4bOfES2YfyalG/3m4IgABOybMINSlJBvrHxm6/YsNCeu6+kc2DZacN8v4NKZT7gSMrQO3PQzrxcGIn70D+xqfLu3xPfRFEiAh3J+J7g2WImJKsmxVmpywm1Y=}
