travis:
  secure:
    BINSTAR_TOKEN: czX1FoECi9OxOSk+UKFx8oNefL1JNQmhnVnu40Ht5X8KlXbavN/iyhxfGQbfaKs9FUf/2JD/Qm72a+6pujUu4E4oyPkA1uS/fRoWvIXIBCypYuJHD1W/O0pXS76MH2gJK0KRoQUPp9pRodaozcpPoIR3/dmILEHIw0BWkqkAGw2PpyP+giv5VYkxa7vyl1150N3YuRCvm8u1ftgpXLPreR68vV0fOOrwoxdE/QIsQL3akiPGgKmb1nfX7hdzlDzkg8AN+W8WeGo90i3M3atxBN5Hlyi8acarlbRywkxDtvBKow5Aich2C+lc+2VCtSDzyFGFHLFo8s9ySqh8X9n9EYhee2tG+F+PTaGY8nMqQnKvH7pDrYsu8fedh6301NPF/ha/HARKY2hcokIdDKdSaGElSJjijwH35XbCkJP86i4eYEmO9Xy0+enNW2V8wXkUdrqBfAMKq980q9KCYS4dg1fT+kNWeWKoZRbOReDU8ucUycBhXIGB6OkRNJfAQntEqNSqRLpl7VkB7nFSXCFwjCY9CjjASbSmzHBDmC9gFyju0bZzmHUOI+UHz06iL+ge+R7z/JvGnGd5GDHeMRNd0ki+Sm59Ze4wXfJe2iPY8/bkzWfStYTcmcMatZE2AgRVIm35/Gw/9U1Rt6qQueH+58GNVlNMnYjhPQZliNjpGG4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
