appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: F6zQQUkQYoI2HREzFUJyES9RerbLuj2lKGaFNf/MP5VpTilEdMMYjpntJ0R6rv5kekdyY5peMDnrjCrshsmqlS4QJufEYM6+guzUxQiQHs2SjwYNY0ZEObgCBVwaHoVTK+iwg3E31uliEOlxQnVon1EAasOXQx+s9YlPSBm5DLShSueBjVAazVnsIuUtp7wgIfCkJ1PLXkwzaJZ6KWFoCtV9Xe4F269lYS5uHopsiqLaSTBVk3Br5bhPtzwMaPJbNROfydDFLHfDMwGjMt4CKwRt4A8BUOYoCyjH59sjqpIrUyflWjRcurBeraOvjl4REdJyCaCDsGLhujX1SJnl823QiOfwVy9Dg/3gbmA0SMvg5ZBb5K0uZCjiKXJAXXM7A6jtkn7fkzc/UHzLW9oVtQ7MJjGm8mSHq6/L2N6TjxyIbdpF+0RXfDSTHP364gPmmdHuu8p2blVpVJlA8qLrw0WTio84ZG7psWOFe4u8EprPM3dx6R5SIAq7zX9CF8vdXldm5fa4RLnDYEf+J+5LSiPW1cqb8GoMiFpDS5YD/TW/G7YJFSaWP126hc+i93T8As6esvhZrVARqfVi674oNecHSYtGP5m5B3WAL7mZCHjNrfd54PVVDwrK2SfOf0OAP0VgeOdb2HVaeEdiigf62bOrfw3tc3aq50Q5LoCP1jA=}
conda_forge_output_validation: true
bot:
  automerge: true
