travis:
  secure:
    BINSTAR_TOKEN: C+vSEFu6WmjjQMnB7jkpmsWc7csirvvGMT5qCY+siuSo94v1CdiN+nl/rLVQnzEFPEofoEOpq8S6Bv4xjsvw/Se5LyNpdszfOkT2/HX2GSosvwz5mYwZp2b3wu8bofIDrWzkZKptTGQLsuvy/DVf6DQOXPzCmBq1yDKYeHK+6qnN8jmUV/P16sJrNcQ8nq9gXa8FduIfxIC7cojyhqhypFLMYd8/+6HYucnVHUTdMn4QKnuvfyu+UT3ga77oOzxyBkd8B1wcCv7NRyBa5qZX1OyPkShsWEaZmFOjgTw7MrTRVGdl3dhiALQCcFF+fmY7p4ZMBPDDJFFULwnmhvJJJk2Qsf1ODy//3lPo69ogQgybKtuE9yTFy1tsaDY/2ODiGNyrKq1OowOiGe7oMlSemFQ7YORlRQAJcanuUgqy2D8r/Nwca9Za6RFPAp7duY9set9xzjVVelyVKs9i8/gPwTZaJkNVrPGxp5J1w8mtMQAk4jxiiVbbDC165dkzF8ujgwkvbjXn/1OzywqgyOJ1TaoXrET3xMV0spZjdVbGTLuWNzWo+0CrswB21uigFqmg3AF6PgIXAlxXVDsA/5/zUc0ZQ/koE5lqSwlrOFqtB+ER9mS1KauvhKN/Mkyblz6Kclf3Ncm+i17U8D/ieITuhn2a50abM0WtT5HSIw3Tx80=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
