{% set version = "0.4.2" %}

package:
  name: tokenizers
  version: {{ version }}

source:
  - url: https://github.com/huggingface/tokenizers/archive/python-v{{ version }}.tar.gz
    sha256: acf27430082d04b2d5243da3658bedccf19a9cad4adc224126084ec5e4146f09
    folder: tokenizers
    patches:
      - 0001-Use-local-pyo3-package.patch
  - git_url: https://github.com/colesbury/pyo3
    git_rev: master
    folder: pyo3

build:
  number: 1
  script: "cd tokenizers/bindings/python && {{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - rust-nightly >=1.43.0  # from -c powerai
  host:
    - python
    - pip
    - setuptools-rust  # requires -c conda-forge (for noarch semantic_version)
  run:
    - python

about:
  home: https://github.com/huggingface/tokenizers
  summary: Fast State-of-the-Art Tokenizers optimized for Research and Production
  license: Apache License 2.0
  license_family: Apache
  description: |
    Provides an implementation of today's most used tokenizers, with a focus on
    performance and versatility.

extra:
  recipe-maintainers:
    - colesbury
