travis:
  secure:
    BINSTAR_TOKEN: X0iDyedFnlG96WUTYQocH1gJk+KwAHpxpUEDHYA2/1Ns7IDp2OOr2CMVRqff245X4ta+BHuwX+SeKx7hSzn4LqKYQcuiTbvufGgZfeuqehV/5aShoPw2bVn92O6ffFnpA4T1ka7IbcrgIOpgGfMtLtreOrzDdR1hrOFXqO2ZSqpdTNBl8W2Gx5yupL3dZJ/6ScqV1EKKMuOiBg47HLTBTVwCfNOV/Nxak8ialcR/INIfrF3GJGdS3xou6YV2YOTZWmoznA9V7H+RvQhQKJQe/muBCBSa2IAw0IVXrlfTVya4NaH9Fd2jfUBqfuhA1sJFrt/qsKWYj2vNlXwrscLfkBMDma5SAIGmpjtUUBkiFa8SgCatW921m2LJGZ3xCwPxJsed4wEcm8GW1uMU07w8RWjP3hIfMjPOZuWS2ec+27zbuv6/jXaQzRL/EmUITRuIG5+WI4xsSnl6qMdj64KR0x8ty6d+QQQsPF/hWiiwZqa+QaWSH60DYx1T/UeNnwBvBuCfGXLvdGf3Vo/skISzExDkI7vWkfMFEwrg3up532u066X7wuWjIr9iv9ODWjmDrITa01jfziTLBDNcSO7lI/nHljXXb7PmTtp1OxFl6FFCme0sX3PQe3AEpKMHOJIhUQ38fZatAdaaGd8Kppk28WyoPv5fcOMLJIAjcgUhib0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
