appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: wVrn5ydCtkOvGcnxQdEFPrqe09RbBxgBav2PZ0jQqSVidcr0mQG8TBjTHtLv7Hkzg/xx7we5XE8cHo1uyQuz/+COwWTnivHroT7E1/Vh+8p/89qRPwLgz4VR/N+v8SvWRmQhcDsDedW9ZMP+1FRZ9NvdjtJypq9VAm3A3IyB5WyntMq/KV9B+brZgRtaA0yl0zNETJjOcHw2mKLEOvC05g3Y9Sa8gIPyPXte265XO4DLY8kv9eY5xgqB0bzOrf24pAO4wuuXQGZ9Ajr36oV8iNOiT+hgpKb5j1YjQM1104AIBQ+rPRqvX/+a9ii/F2IQep2uN9ukRlTolQtQ5mMY09DLzHbmjnm4q+wz3cY95qCPsqsQbjROZ6WBFrKlKsTCPloCvKRFg5M4tByVE6nxzpf5py72UMhiChn8UN7iNpz990JRPXuhTwAc58LhQQM4TV3anPR75RE8WvIlPEWRpfWIAkYsBJnZL5UGbyZIL8UjifzapjHNrBvrVwfBHuXOaGnL+9liHBFdKXe1mwbr0oz+wnie4it/lIeprCA+y7EhiAkXcSP9g8QOJe0dzB2IcZhTBJR+3r6CBw19mu+jkzUhcRy2qY7vFYDgdbvnX2tR95rG6J9dvPACS4r3TfheZPP8vGRVlNIV/BiYGS91w38LMgwljj6iRjYdgxvh/PQ=}
provider:
  win: azure
conda_forge_output_validation: true
