travis:
  secure:
    BINSTAR_TOKEN: q48hR6+qKPtY90GdtVp1vtn19NX9ogYcN9PHgsDGjgPRw0uvc7wvoaC/l9Kdqn3kXFclq0pQsX4k4F3nKANBdu6eVU4UImovkSAlp8Og9m0u1hQkPkhNnwV6INLlPWXxgUqCrQkfwtbCDbmytwjU0YeTZpEH5VdlTSROvYiuNCXD06AgNG/3AuP8ooO57Gabv110OHe1zJM5tUds7rIglLUSE9HyvjbtfZN+6H9px9+8E5NOA82+9Ps0ax46dD+frSgEh1Ka+GolB8qOOxgZR3eGdf6IkneV5WF6ax3PyXrJcoR+TlapDJchxX2BWnxG8Ae3YLY8Nk7hawfnJJ33I0akJOZCNBcIEcY2JoKJwTfXdzyj6sH2Lu39oO6/MRQ+RJuM2Tf4mxBZqz+kjH9ncDjJV0xiwZPDDKM0liQ+MbwgvtJFbc7k2Hmxxoc6ZjP9IqRBAkbFjdN9BroE0XP19wcCLQ55YAIxcRY+IvqWtYE5rtb2QJSEMDiZu5id+bmpf8yV/ZJ7C8yn3l6c+T+tnspJNCq5bAfTNv1gVc+yTKonX3GK1k+DVuNabPWiz/GPM+Q67FEKDd7e6j6Y0bcr9JHh4adXK0589ZilA5gs3ACEdQdiRBVE7C3ATNyC04oV1nh9BOR4eYJGXVA8lv6F3xS7/mmDHTIdBZx5ws6s9eo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
